// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFtl8Gj1n2KAYJYNcKKcncwjt0ShSQryU',
    appId: '1:779063517283:web:ce0f3292030ae182ce9856',
    messagingSenderId: '779063517283',
    projectId: 'storeapp-9c602',
    authDomain: 'storeapp-9c602.firebaseapp.com',
    storageBucket: 'storeapp-9c602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEr3quLb1WoRFtOTOAeqRlhJKOa0Lnuc4',
    appId: '1:779063517283:android:8e688e3f468854ddce9856',
    messagingSenderId: '779063517283',
    projectId: 'storeapp-9c602',
    storageBucket: 'storeapp-9c602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqRD9ciXgr1AzTfAH-wkmVtCO1yzn0Z-M',
    appId: '1:779063517283:ios:6ee3cb813871bb78ce9856',
    messagingSenderId: '779063517283',
    projectId: 'storeapp-9c602',
    storageBucket: 'storeapp-9c602.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqRD9ciXgr1AzTfAH-wkmVtCO1yzn0Z-M',
    appId: '1:779063517283:ios:6ee3cb813871bb78ce9856',
    messagingSenderId: '779063517283',
    projectId: 'storeapp-9c602',
    storageBucket: 'storeapp-9c602.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFtl8Gj1n2KAYJYNcKKcncwjt0ShSQryU',
    appId: '1:779063517283:web:4c59071b0f946ba1ce9856',
    messagingSenderId: '779063517283',
    projectId: 'storeapp-9c602',
    authDomain: 'storeapp-9c602.firebaseapp.com',
    storageBucket: 'storeapp-9c602.appspot.com',
  );

}